create table Customer (
	CustomerID BIGSERIAL PRIMARY KEY,
	First_Name VARCHAR(50) NOT NULL,
	Last_Name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	DOB DATE NOT NULL,
	Shipping_Adress VARCHAR(50) NOT NULL,
	Billng_Adress VARCHAR(50) NOT NULL
);
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Terese', 'Dearlove', 'tdearlove0@amazonaws.com', '08/29/1978', '72 5th Junction', '82 Clemons Court');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Peg', 'Ruffli', 'pruffli1@wp.com', '06/07/1967', '160 Cordelia Way', '51797 Ludington Lane');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Herby', 'Higgan', 'hhiggan2@addthis.com', '05/25/1966', '7769 Elmside Trail', '7 Leroy Trail');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Allen', 'de Werk', 'adewerk3@usa.gov', '11/28/1950', '27187 Granby Circle', '421 Sachtjen Alley');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Tabbitha', 'Ertel', 'tertel4@slate.com', '10/16/1997', '822 Bay Parkway', '807 Ridgeview Trail');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Anthony', 'McKniely', 'amckniely5@techcrunch.com', '09/06/1985', '47528 Mayer Crossing', '57170 Toban Lane');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Nikki', 'Lepper', 'nlepper6@hao123.com', '04/10/1967', '7095 Gerald Parkway', '76 Anthes Lane');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Derwin', 'Denyukin', 'ddenyukin7@home.pl', '04/29/1953', '53 Ludington Road', '23 Huxley Center');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Franzen', 'Fortnum', 'ffortnum8@zdnet.com', '12/30/1969', '63 Norway Maple Way', '5814 Buell Alley');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Madelena', 'Peschmann', 'mpeschmann9@freewebs.com', '11/26/1974', '45732 Northridge Center', '5822 Carberry Trail');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Shelia', 'Bayne', 'sbaynea@netscape.com', '02/12/1982', '4 Truax Junction', '73559 Emmet Parkway');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Leoline', 'Dorrins', 'ldorrinsb@google.nl', '06/16/1982', '58013 La Follette Point', '3280 Burning Wood Place');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Kathlin', 'Bealton', 'kbealtonc@oakley.com', '05/28/1986', '3010 Del Mar Terrace', '1 Mcbride Park');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Haroun', 'Beade', 'hbeaded@hatena.ne.jp', '05/08/1957', '8878 Prairieview Drive', '5992 Talmadge Junction');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Rosetta', 'Sallnow', 'rsallnowe@youtu.be', '03/24/1960', '2114 Lotheville Crossing', '21 Talmadge Trail');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Batholomew', 'Hearons', 'bhearonsf@howstuffworks.com', '02/10/1961', '1 Sachs Park', '49 New Castle Pass');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Dotti', 'Loudiane', 'dloudianeg@wix.com', '02/11/1967', '41449 Luster Hill', '0906 Marcy Way');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Arlen', 'Fenelow', 'afenelowh@51.la', '08/11/1959', '8501 Roxbury Way', '98 Forest Dale Road');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Camella', 'Inkpen', 'cinkpeni@sakura.ne.jp', '09/08/1966', '21256 Starling Lane', '782 Declaration Way');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Maurine', 'Leslie', 'mlesliej@so-net.ne.jp', '02/28/1994', '85 Stone Corner Hill', '3 South Hill');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Fleurette', 'Canty', 'fcantyk@jugem.jp', '01/04/1995', '498 Schmedeman Alley', '3820 Doe Crossing Point');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Langsdon', 'Osmant', 'losmantl@narod.ru', '08/05/1956', '23787 Beilfuss Place', '2 Bluestem Pass');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Tiena', 'Chevis', 'tchevism@bloglines.com', '01/22/1994', '663 Vernon Circle', '925 Manitowish Court');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Kial', 'Gabrieli', 'kgabrielin@123-reg.co.uk', '09/09/2001', '7 Ronald Regan Circle', '2679 Kim Pass');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Elisha', 'Sustin', 'esustino@admin.ch', '07/12/1957', '14 Saint Paul Crossing', '1 Spohn Place');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Brittan', 'Pearmain', 'bpearmainp@cbsnews.com', '07/25/1980', '1450 Transport Circle', '439 Darwin Alley');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Johnath', 'Micklewright', 'jmicklewrightq@google.ru', '07/21/1997', '6210 Becker Center', '55641 Michigan Center');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Edmon', 'Troke', 'etroker@bing.com', '07/26/1958', '24910 Cardinal Crossing', '063 Mayer Avenue');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Antony', 'Mattiussi', 'amattiussis@youtube.com', '08/08/1955', '31 Schurz Alley', '14 Golf Course Point');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Brana', 'Eckery', 'beckeryt@amazon.co.jp', '09/26/1985', '59027 Melody Park', '945 Wayridge Terrace');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Kane', 'Crossgrove', 'kcrossgroveu@merriam-webster.com', '03/09/2001', '200 Bluejay Alley', '781 Brentwood Road');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Dorette', 'Volonte', 'dvolontev@newsvine.com', '07/15/1950', '8 Sunbrook Terrace', '7146 South Street');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Adora', 'Madle', 'amadlew@nature.com', '07/01/1953', '7 Sutherland Pass', '8 Merry Parkway');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Lolly', 'Oubridge', 'loubridgex@dot.gov', '01/01/1981', '35 Melody Terrace', '18 Eagle Crest Court');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Allissa', 'Styche', 'astychey@sakura.ne.jp', '03/26/1963', '3 Kenwood Center', '0 Anthes Way');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Fredrika', 'Windrus', 'fwindrusz@scribd.com', '07/03/1957', '15771 Kensington Center', '47 Summer Ridge Pass');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Frederik', 'Croce', 'fcroce10@epa.gov', '01/28/1995', '6827 Novick Court', '3045 Washington Junction');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Gregorio', 'Panichelli', 'gpanichelli11@google.com.hk', '12/21/1951', '33 Trailsway Avenue', '08 Rigney Park');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Darline', 'Kingsford', 'dkingsford12@istockphoto.com', '07/14/1976', '10002 Sunnyside Junction', '6 Menomonie Junction');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Fiann', 'Keyho', 'fkeyho13@salon.com', '03/02/1954', '08 Mayer Plaza', '55 Old Shore Drive');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Nicolle', 'Gummie', 'ngummie14@nationalgeographic.com', '01/11/1970', '6 Waubesa Park', '16 Moulton Court');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Yvon', 'Legonidec', 'ylegonidec15@google.co.jp', '04/30/1955', '390 Buena Vista Pass', '87 Mallory Way');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Berkie', 'Blenkiron', 'bblenkiron16@soundcloud.com', '06/20/1990', '00 Straubel Park', '1 Pankratz Pass');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Tedra', 'Herreros', 'therreros17@booking.com', '05/13/1982', '44566 Cascade Point', '724 Cordelia Terrace');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Garreth', 'Hillyatt', 'ghillyatt18@jigsy.com', '01/04/1963', '4 Homewood Crossing', '7 Westend Parkway');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Mallissa', 'Liveley', 'mliveley19@timesonline.co.uk', '10/28/1953', '589 Meadow Ridge Street', '0683 Manufacturers Avenue');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Lyn', 'Foote', 'lfoote1a@google.co.jp', '04/15/1986', '23473 Schmedeman Avenue', '536 Algoma Avenue');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Ramon', 'Scardafield', 'rscardafield1b@marketwatch.com', '11/21/1999', '6551 Buell Circle', '7 Stoughton Junction');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Fallon', 'Lewnden', 'flewnden1c@taobao.com', '12/31/1963', '499 Old Gate Parkway', '89793 Melvin Alley');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Wallis', 'Gerwood', 'wgerwood1d@cnn.com', '05/11/1997', '5798 Warner Street', '7298 Almo Way');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Minette', 'O''Keaveny', 'mokeaveny1e@skyrock.com', '03/01/1980', '8472 Kinsman Avenue', '879 Anthes Pass');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Abbot', 'Bignell', 'abignell1f@eepurl.com', '12/09/1967', '70940 Russell Road', '5 Waywood Circle');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Vladamir', 'Frayn', 'vfrayn1g@simplemachines.org', '03/03/1952', '242 Loomis Court', '69 Forster Road');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Guy', 'Leonard', 'gleonard1h@123-reg.co.uk', '09/11/1980', '29 Chinook Point', '8 Basil Parkway');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Sherie', 'Churn', 'schurn1i@geocities.com', '01/22/1965', '0 Vidon Pass', '3 Lunder Lane');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Renault', 'Fernez', 'rfernez1j@amazon.co.uk', '07/30/1971', '70467 Sutteridge Point', '70 Little Fleur Junction');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Nahum', 'Edscer', 'nedscer1k@patch.com', '10/11/1993', '401 Arapahoe Crossing', '0 Jana Place');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Ross', 'Grammer', 'rgrammer1l@apache.org', '09/27/1992', '924 Artisan Place', '98951 Luster Park');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Tadeo', 'McClay', 'tmcclay1m@discovery.com', '10/30/1974', '550 Center Trail', '582 Welch Alley');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Jere', 'Isakovic', 'jisakovic1n@dailymail.co.uk', '07/21/1967', '49 5th Terrace', '2540 Cascade Center');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Hyacinth', 'Gealle', 'hgealle1o@4shared.com', '04/16/1955', '711 Lotheville Road', '2540 Sachtjen Trail');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Halsey', 'Francey', 'hfrancey1p@topsy.com', '10/15/1952', '9 Carpenter Crossing', '2550 Oakridge Plaza');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Eleanor', 'Redgrove', 'eredgrove1q@samsung.com', '03/01/1988', '9495 Blue Bill Park Way', '13 Ridgeview Alley');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Selig', 'Plumley', 'splumley1r@smugmug.com', '12/21/1967', '4719 Union Center', '68 Mayer Lane');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Pernell', 'Jerman', 'pjerman1s@people.com.cn', '04/20/1984', '0 Shasta Circle', '795 Ronald Regan Avenue');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Howard', 'Euston', 'heuston1t@tripod.com', '09/11/1979', '022 Rockefeller Junction', '135 David Alley');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Osmond', 'Attenburrow', 'oattenburrow1u@nba.com', '12/27/1953', '534 Pierstorff Trail', '75 Valley Edge Court');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Mallory', 'Blaisdale', 'mblaisdale1v@netscape.com', '08/23/1959', '93 Waxwing Way', '71706 Russell Lane');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Roosevelt', 'Fullard', 'rfullard1w@kickstarter.com', '11/07/1957', '60122 Crest Line Park', '254 Northland Road');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Clem', 'Robelow', 'crobelow1x@census.gov', '07/20/1954', '7 John Wall Court', '6856 Coolidge Point');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Pansie', 'Golightly', 'pgolightly1y@wufoo.com', '02/07/1973', '7992 Sommers Parkway', '8365 Prentice Center');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Nico', 'Bilston', 'nbilston1z@aol.com', '12/20/1997', '8 Boyd Hill', '27 Pond Road');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Caty', 'Badcock', 'cbadcock20@deviantart.com', '01/08/1952', '9 4th Place', '9219 Kim Center');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Jeanine', 'Glanfield', 'jglanfield21@nature.com', '01/30/1960', '47 Buell Road', '1770 Waywood Place');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Denny', 'Kierans', 'dkierans22@taobao.com', '02/11/1975', '50 Hollow Ridge Hill', '602 Troy Point');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Agathe', 'Wilsey', 'awilsey23@cargocollective.com', '02/23/1965', '3956 Onsgard Court', '529 Messerschmidt Place');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Elysee', 'Hempel', 'ehempel24@howstuffworks.com', '08/01/1998', '2 Spenser Circle', '5013 Merrick Circle');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Barth', 'Melrose', 'bmelrose25@sitemeter.com', '01/19/1968', '76 Homewood Plaza', '26 Linden Crossing');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Elysee', 'Stretton', 'estretton26@shinystat.com', '01/14/1966', '77380 Declaration Crossing', '9 Shasta Way');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Nettle', 'Lounds', 'nlounds27@oaic.gov.au', '07/20/1956', '97 Fairview Center', '2948 Lakewood Center');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Joseito', 'Quodling', 'jquodling28@360.cn', '02/04/1991', '0667 Thompson Park', '1 Village Junction');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Dinny', 'Basil', 'dbasil29@google.es', '02/07/1975', '1 Nevada Crossing', '758 Oxford Plaza');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Marthena', 'Densumbe', 'mdensumbe2a@pinterest.com', '06/17/1952', '7 Badeau Street', '478 Canary Lane');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Madonna', 'Meah', 'mmeah2b@parallels.com', '01/26/1955', '908 Scoville Lane', '448 Duke Way');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Tamar', 'Beacham', 'tbeacham2c@xing.com', '01/14/1999', '2901 Tennyson Hill', '39 Coleman Court');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Parnell', 'Maggiori', 'pmaggiori2d@army.mil', '05/14/1960', '1 3rd Road', '251 Towne Crossing');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Astra', 'Pickthorn', 'apickthorn2e@networksolutions.com', '08/23/1954', '8 Bluestem Parkway', '155 Weeping Birch Junction');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Devonne', 'Liptrot', 'dliptrot2f@jigsy.com', '06/24/1960', '2 Oneill Park', '95 Cody Street');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Perl', 'Denness', 'pdenness2g@cnbc.com', '12/18/1994', '723 Oxford Alley', '599 Gulseth Pass');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Roscoe', 'O''Nions', 'ronions2h@dedecms.com', '02/23/1976', '728 Marcy Hill', '26 Pawling Alley');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Lenee', 'Charer', 'lcharer2i@bbc.co.uk', '09/05/1979', '6 Darwin Street', '666 Aberg Circle');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Abdul', 'Mariolle', 'amariolle2j@shop-pro.jp', '12/27/1999', '1 Havey Lane', '556 Bellgrove Parkway');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Chris', 'Bowra', 'cbowra2k@reddit.com', '07/04/1951', '05823 Kinsman Hill', '7603 Bowman Trail');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Roseann', 'Mawne', 'rmawne2l@list-manage.com', '03/01/2000', '2 Melby Circle', '97 Kings Drive');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Ingeborg', 'Marquiss', 'imarquiss2m@webmd.com', '10/18/1995', '59 Everett Terrace', '7530 Loeprich Way');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Kessiah', 'Gowman', 'kgowman2n@mashable.com', '05/18/1968', '5 Garrison Crossing', '8513 Bultman Road');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Nani', 'Rugiero', 'nrugiero2o@exblog.jp', '10/03/1997', '9439 Del Sol Pass', '115 Thackeray Junction');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Cross', 'Lumbers', 'clumbers2p@wunderground.com', '04/29/1973', '5 Sycamore Hill', '93 Amoth Lane');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Joseito', 'Nulty', 'jnulty2q@miitbeian.gov.cn', '09/02/1972', '1879 Fallview Junction', '414 Thompson Pass');
insert into Customer (First_Name, Last_Name, email, DOB, Shipping_Adress, Billng_Adress) values ('Web', 'Hawse', 'whawse2r@myspace.com', '04/28/1951', '710 Shopko Parkway', '3 Nevada Road');
